#! /bin/bash
#############################################################################
#                                                                           #
#******This bash script is written by VR<vrnithinkumar@gmail.com>***********#
#               copyright@GNU GENERAL PUBLIC LICENSE                        #			#############################################################################
if [ $# -lt 2 ]
then
echo -e "$0 : Invalid Input.....\n You must give two input"
exit 1
fi
function fungadd()
{
 echo "Sum of $1 and $2 = `expr $1 \+ $2` "
 }
 fungadd $1 $2
