#! /bin/bash
#############################################################################
#                                                                           #
#******This bash script is written by VR<vrnithinkumar@gmail.com>***********#
#               copyright@GNU GENERAL PUBLIC LICENSE                        #			#############################################################################
bash --rcfile <(
echo -e "PS1='\e[1;32m*vrnithins*...\e[0m'"
echo -e "export PATH=$PATH:./:../"
echo "it is cool i think"
)
